// Code generated by Kitex v0.4.4. DO NOT EDIT.

package relationservice

import (
	"context"
	relationdemo "douyin_backend_microService/relation/kitex_gen/relationdemo"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Relation(ctx context.Context, Req *relationdemo.RelationActionRequest, callOptions ...callopt.Option) (r *relationdemo.RelationActionResponse, err error)
	GetFollow(ctx context.Context, Req *relationdemo.RelationFollowListRequest, callOptions ...callopt.Option) (r *relationdemo.RelationFollowListResponse, err error)
	GetFollower(ctx context.Context, Req *relationdemo.RelationFollowerListRequest, callOptions ...callopt.Option) (r *relationdemo.RelationFollowerListResponse, err error)
	GetFriend(ctx context.Context, Req *relationdemo.RelationFriendListRequest, callOptions ...callopt.Option) (r *relationdemo.RelationFriendListResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kRelationServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kRelationServiceClient struct {
	*kClient
}

func (p *kRelationServiceClient) Relation(ctx context.Context, Req *relationdemo.RelationActionRequest, callOptions ...callopt.Option) (r *relationdemo.RelationActionResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Relation(ctx, Req)
}

func (p *kRelationServiceClient) GetFollow(ctx context.Context, Req *relationdemo.RelationFollowListRequest, callOptions ...callopt.Option) (r *relationdemo.RelationFollowListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetFollow(ctx, Req)
}

func (p *kRelationServiceClient) GetFollower(ctx context.Context, Req *relationdemo.RelationFollowerListRequest, callOptions ...callopt.Option) (r *relationdemo.RelationFollowerListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetFollower(ctx, Req)
}

func (p *kRelationServiceClient) GetFriend(ctx context.Context, Req *relationdemo.RelationFriendListRequest, callOptions ...callopt.Option) (r *relationdemo.RelationFriendListResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetFriend(ctx, Req)
}
